### ISSUE TITLE
calling just veo_async_write_mem takes much time

### ISSUE THREAD

**Issue by quickwritereader** [SX-Aurora/aveo#28]
recently, I started using the async capabilities of Aveo through veda .
I noticed that without wait logic my async operations still take much time.
in my logs it showed that it depends on the size as well
could you confirm this as well

here is how I am testing.

I added async_mem.c test and also added its name in Makefile

```

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include <urpc_time.h>
#include <ve_offload.h>

/* variables for VEO demo */
int ve_node_number = 0;
struct veo_proc_handle *proc = NULL;
struct veo_thr_ctxt *ctx = NULL;

int veo_init() {
  int rc;
  proc = veo_proc_create(-1);
  if (proc == NULL) {
    perror("ERROR: veo_proc_create");
    return -1;
  }

#ifdef VEO_DEBUG
  printf("If you want to attach to the VE process, you now have 20s!\n\n"
         "/opt/nec/ve/bin/gdb -p %d veorun_static\n\n",
         getpid());
  sleep(20);
#endif
  ctx = veo_context_open(proc);
  if (ctx == NULL) {
    perror("ERROR: veo_context_open");
    return -1;
  }
  return 0;
}

int veo_finish() {
  veo_context_close(ctx);
  veo_proc_destroy(proc);
  return 0;
}

int main(int argc, char **argv) {
  int i, rc, n, peer_id;
  uint64_t ve_buff;
  void *local_buff;
  size_t bsize = 1024 * 1024, res;
  long ts, te;
  double bw;

  if (argc > 1) {
    bsize = atol(argv[1]);
  }

  rc = veo_init();
  if (rc != 0)
    exit(1);

  local_buff = malloc(bsize);

  rc = veo_alloc_mem(proc, &ve_buff, bsize);

  uint64_t req[1];

  ts = get_time_us();
  req[0] = veo_async_write_mem(ctx, (uint64_t)ve_buff, local_buff, bsize);
  te = get_time_us();

  veo_call_wait_result(ctx, req[0], &res);

  printf("veo_async_write_mem: %lu call %zu Bytes  %ld us\n", res, bsize, (te-ts));

  veo_finish();
  exit(0);
}

```

here are my results:

$ ./async_mem
veo_async_write_mem: 0 call 1048576 Bytes  449 us
$ ./async_mem 10485760
veo_async_write_mem: 0 call 10485760 Bytes  1044 us

**Comment by quickwritereader** [comment]
hi team, were you able to check my issue?

**Comment by veos-sxarr** [comment]
Hello.

We, the VEOS development team in NEC, would like to share our view.

However please note that we don't maintain this repository. Our project is here. NEC tests and modifies the AVEO from the original project and release it as a part of VEOS.
https://github.com/veos-sxarr-NEC/aveo

veo_async_write_mem() performs some of operations to write data.
veo_call_wait_result() performs remaining operations to write data.

There is no dedicated thread for asynchronous operations.
Therefore, veo_async_write_mem() is not completely asynchronous.

NEC has tried to create a patch to use a dedicated thread for asynchronous operations.
But, the latency becomes bigger because sleep and wake are required.
So, the current implementation is good for now from the viewpoint of the latency.

We will try to find a good solution to provide complete asynchronous operations.

**Comment by efocht** [comment]
Some further comments.

The async API is asynchronous in the sense of ... you can submit the request and do something else. It is being driven by either other subsequent VEO requests or by a synchronization call like veo_call_wait_result() or veo_call_peek_result(). Eventually, in the stream of offload commands you need to synchronize. Using an async operation without a wait (or vedaCtxSynchronize) makes no sense. Somewhere you need to make sure that it has been done.

A larger memory transfer takes longer time to complete. That is ... physics. From that point of view, what you see is right.

The asynchronicity of the VEDA (and AVEO) operations is in the API and refers to the operations on the VH. Requests in a VEDA stream are still strictly executed one after the other, sequentially! Memory transfers need to be driven from the VE side, so if you want to overlap memory transfer and VE work, you will need to have many rather small transfers and small pieces of work that alternate. The DMA engine can work in the background while the subsequent computation request might have started, but if it is a large transfer which does not fit into one DMA request, we have no additional thread on the VE to drive the transfer in the background. So the overlap of transfer and computation is currently rather small (marginal). We're working to improve that.
